name: deploy

on:
  release:
    types: [created]

env:
  AWS_REGION: ap-northeast-1
  WORK_DIR: ./terraform
  SCRIPT_DIR: ./scripts

jobs:

  execute:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: ${{ env.WORK_DIR }}

    steps:

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.5

      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: npm install
        run: npm install
        working-directory: ${{ env.SCRIPT_DIR }}

      - name: npm download
        run: npm run download
        working-directory: ${{ env.SCRIPT_DIR }}

      - name: init
        run: terraform init

      - name: plan
        run: terraform plan -out="out.plan"

      - name: apply
        run: terraform apply out.plan

      - name: npm upload
        if: always()
        run: npm run upload
        working-directory: ${{ env.SCRIPT_DIR }}
